name = "joshthompson-net"
type = "javascript" # or "webpack" if you plan to use bundling
compatibility_date = "2025-09-10"

# For static sites, define the build output directory
[site]
bucket = "." # or "." if you want the root
entry-point = "."  # optional for pure Pages sites

# Optional: If you want a Worker for additional functionality
# main = "src/index.js"
